name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        npm install
        npx eslint challenge-1/index.js
        npx eslint challenge-2/app.js
        npx eslint challenge-3/app.js
        npx eslint challenge-4/app.js
        npx eslint challenge-5/app.js
