name: ESLint, StyleLint, prettier

on:
   push:
    branches:
    - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
     # Check out the repository
      - uses: actions/checkout@v3
      - run: |
         npm install eslint
         npx eslint . --ext .js,.jsx,.ts,.tsx --fix
    
  stylelint:
    runs-on: ubuntu-latest
    needs: eslint
    name: Run StyleLint
    steps:
     # Check out the repository
      - uses: actions/checkout@v3
      - run: |
         npm install --save-dev stylelint stylelint-config-standard
         npm install --save-dev stylelint-config-prettier
         npx stylelint "**/*.css" --fix
    
  prettier:
    runs-on: ubuntu-latest
    needs: stylelint
    name: Run prettier
    steps:
     # Check out the repository
      - uses: actions/checkout@v3
      - run: |
         npm install --save-dev --save-exact prettier
         npx prettier --write .
    
  s3upload:
    runs-on: ubuntu-latest
    needs: prettier
    name: Upload to S3
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://rishi-js-challenges --delete
 
